### ISSUE TITLE
Updating to Vue 3.4.5 breaks component 

### ISSUE THREAD

**Issue by lagamura** [leezng/vue-json-pretty#264] opened 2024-01-05 15:36 UTC
Updating from Vue 3.3.13 to 3.4.5 breaks functionality of the component throwing the following warning:

`[Vue warn]: Missing ref owner context. ref cannot be used on hoisted vnodes. A vnode with ref must be created inside the render function. `

**Comment by RobsonMi** [comment] 2024-01-14 00:03
Vue 3.4.3 seems to be the last without this warning. Would be lovely to get this sorted, even if it's just a warning.

**Comment by leezng** [comment] 2024-01-17 08:52
Can anyone provide an example?
by https://codesandbox.io/

**Comment by leezng** [comment] 2024-01-17 09:12
After upgrading the vue version, the warning has disappeared.
Maybe it's related to this https://github.com/vuejs/core/issues/10012

**Comment by RobsonMi** [comment] 2024-01-17 13:48
I did test with Vue 3.4.14 just now and warning is still there

**Comment by tpoxa** [comment] 2024-01-27 20:50
`3.4.15` - still there

**Comment by RobsonMi** [comment] 2024-02-12 21:37
Hi @leezng ! I did try to reproduce on the stackblitz you linked but couldn't. Perhaps full contents of warning from my project will contain some clues?

```
[Vue warn]: Missing ref owner context. ref cannot be used on hoisted vnodes. A vnode with ref must be created inside the render function. 
  at <Tree key=0 ref="jsonPretty" data= 
Object { timestampFormatted: "2024-02-12 18:08:41.539", timestamp: 1707761321539, frame: 29501, system: {…}, location: {…}, speed: {…}, power: {…}, weights: {…}, lights: {…} }
  ... > 
  at <BaseTransition onEnter=fn<onEnter> onLeave=fn<onLeave> appear=false  ... > 
  at <Transition css=false appear=false onEnter=fn<onEnter>  ... > 
  at <QSlideTransition duration=undefined onShow=fn<onShow> onHide=fn<onHide> > 
  at <QExpansionItem dense="" class="log-item no-shadow q-px-sm q-py-xs" onShow=fn  ... > 
  at <LogItem key=7 event= 
Object { id: 7, type: "lights", payload: {…}, createdAt: "2024-02-12T18:08:42.460Z", title: "Lights", details: "Landing: OFF => ON<br/>Strobe: OFF => ON", data: {…} }
 > 
  at <AsyncComponentWrapper key=7 event= 
Object { id: 7, type: "lights", payload: {…}, createdAt: "2024-02-12T18:08:42.460Z", title: "Lights", details: "Landing: OFF => ON<br/>Strobe: OFF => ON", data: {…} }
 > 
  at <QList class="q-px-lg q-py-sm q-gutter-y-sm" > 
  at <BaseTransition onEnter=fn<onEnter> onLeave=fn<onLeave> appear=false  ... > 
  at <Transition css=false appear=false onEnter=fn<onEnter>  ... > 
  at <QSlideTransition duration=undefined onShow=fn<onShow> onHide=fn<onHide> > 
  at <QExpansionItem key=9 dense="" class="col-12 no-shadow q-px-sm q-py-xs" > 
  at <QCard class="main-card" > 
  at <QPage class="row justify-center" > 
  at <Review onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< 
Proxy { <target>: {…}, <handler>: {…} }
 > > 
  at <RouterView> 
  at <QPageContainer> 
  at <QLayout view="hHh LpR lff" > 
  at <MainLayout onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< 
Proxy { <target>: {…}, <handler>: {…} }
 > > 
  at <RouterView> 
  at <App>
  ```

**Comment by ivanjaros** [comment] 2024-02-22 08:45
Same as robson, this just blew up in my face out of nowhere. pretty 2.3.0, vue 3.4.19

**Comment by leezng** [comment] 2024-02-23 07:30
Have you used dynamic components, such as for loops or asynchronous rendering, such as: https://stackoverflow.com/questions/76671447/missing-ref-owner-context-in-production

Can you provide your usage, including some context?

**Comment by NicolasReibnitz** [comment] 2024-02-27 16:35
I'm on Vue v3.4.20 (the latest), and the problem comes up instantly, as soon as you pop in vue-json-pretty (v2.3.0). 


![CleanShot 2024-02-27 at 11 32 59@2x](https://github.com/leezng/vue-json-pretty/assets/20308845/bf405e42-e565-46a4-a9e2-179a5b5fcbfb)

Nothing else is in App.vue.

![CleanShot 2024-02-27 at 11 33 40@2x](https://github.com/leezng/vue-json-pretty/assets/20308845/5e6d2ef5-0182-4cc6-99d1-d8ff4e173507)

I hope this helps. Thanks!

**Comment by leezng** [comment] 2024-02-29 06:49
@NicolasReibnitz What is your vite version?

**Comment by NicolasReibnitz** [comment] 2024-02-29 15:09
> @NicolasReibnitz What is your vite version? Is ssr used?

That'd be v2.9.17.

Seems rather old, doesn't it? Apparently, [@quasar/app-vite](https://www.npmjs.com/package/@quasar/app-vite) didn't update the Vite dependency for quite some time. 🤷

**Comment by ivanjaros** [comment] 2024-03-07 06:48
i was able to update to vite 2.9.17, vue 3.4.21, pretty 2.3.0 but no change. still broken. i will be moving to another library.

**Closed** 2024-03-07 08:08 UTC

**Comment by tpoxa** [comment] 2024-03-07 18:41
Update to `2.4.0-beta.1` helped to get rid of the warnings, thanks @leezng
