### ISSUE TITLE
could not import due to `TypeError: (0 , o.defineComponent) is not a function`

### ISSUE THREAD

**Issue by badbye** [leezng/vue-json-pretty#105] opened 2021-01-09 04:09 UTC
```
import VueJsonPretty from 'vue-json-pretty';
import 'vue-json-pretty/lib/styles.css';
```

![image](https://user-images.githubusercontent.com/3295865/104082759-a8b3bb80-5273-11eb-8a50-a1c392c0824d.png)

**Comment by leezng** [comment] 2021-01-10 09:01
Duplicate of #99

**Closed by leezng** 2021-01-10 09:01 UTC
